[07/Sep/2017 14:47:28] INFO [restaurantes.views:20] 2017-09-07 14:47:28 - se ha consultado la página de inicio
[07/Sep/2017 14:47:30] INFO [restaurantes.views:48] 2017-09-07 14:47:30 - se ha consultado la página de restaurantes
[07/Sep/2017 14:48:39] INFO [restaurantes.views:48] 2017-09-07 14:48:39 - se ha consultado la página de restaurantes
[07/Sep/2017 15:08:24] INFO [restaurantes.views:91] 2017-09-07 15:08:24 - se ha consultado la página de add restaurante
[07/Sep/2017 15:08:51] INFO [restaurantes.views:91] 2017-09-07 15:08:51 - se ha consultado la página de add restaurante
[07/Sep/2017 15:08:52] ERROR [django.request:124] Internal Server Error: /restaurantes/add/
Traceback (most recent call last):
  File "/home/pablo/SSBW/lib/python3.5/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/home/pablo/SSBW/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/pablo/SSBW/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/pablo/SSBW/lib/python3.5/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/pablo/SSBW/sitio_web/restaurantes/views.py", line 99, in add
    r = form.save()
  File "/home/pablo/SSBW/sitio_web/restaurantes/forms.py", line 19, in save
    tree = etree.parse(req)
  File "src/lxml/lxml.etree.pyx", line 3442, in lxml.etree.parse (src/lxml/lxml.etree.c:81716)
  File "src/lxml/parser.pxi", line 1811, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:118635)
  File "src/lxml/parser.pxi", line 1837, in lxml.etree._parseDocumentFromURL (src/lxml/lxml.etree.c:118982)
  File "src/lxml/parser.pxi", line 1741, in lxml.etree._parseDocFromFile (src/lxml/lxml.etree.c:117894)
  File "src/lxml/parser.pxi", line 1138, in lxml.etree._BaseParser._parseDocFromFile (src/lxml/lxml.etree.c:112440)
  File "src/lxml/parser.pxi", line 595, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:105896)
  File "src/lxml/parser.pxi", line 706, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:107604)
  File "src/lxml/parser.pxi", line 633, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:106415)
OSError: Error reading file 'http://maps.googleapis.com/maps/api/geocode/xml?address=#00nuevoMalaga': failed to load HTTP resource
[07/Sep/2017 15:08:52] ERROR [django.server:131] "POST /restaurantes/add/ HTTP/1.1" 500 76459
[07/Sep/2017 15:09:35] INFO [restaurantes.views:91] 2017-09-07 15:09:35 - se ha consultado la página de add restaurante
[07/Sep/2017 15:09:36] ERROR [django.request:124] Internal Server Error: /restaurantes/add/
Traceback (most recent call last):
  File "/home/pablo/SSBW/lib/python3.5/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/home/pablo/SSBW/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/pablo/SSBW/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/pablo/SSBW/lib/python3.5/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/pablo/SSBW/sitio_web/restaurantes/views.py", line 99, in add
    r = form.save()
  File "/home/pablo/SSBW/sitio_web/restaurantes/forms.py", line 19, in save
    tree = etree.parse(req)
  File "src/lxml/lxml.etree.pyx", line 3442, in lxml.etree.parse (src/lxml/lxml.etree.c:81716)
  File "src/lxml/parser.pxi", line 1811, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:118635)
  File "src/lxml/parser.pxi", line 1837, in lxml.etree._parseDocumentFromURL (src/lxml/lxml.etree.c:118982)
  File "src/lxml/parser.pxi", line 1741, in lxml.etree._parseDocFromFile (src/lxml/lxml.etree.c:117894)
  File "src/lxml/parser.pxi", line 1138, in lxml.etree._BaseParser._parseDocFromFile (src/lxml/lxml.etree.c:112440)
  File "src/lxml/parser.pxi", line 595, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:105896)
  File "src/lxml/parser.pxi", line 706, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:107604)
  File "src/lxml/parser.pxi", line 633, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:106415)
OSError: Error reading file 'http://maps.googleapis.com/maps/api/geocode/xml?address=#00nuevoMalaga': failed to load HTTP resource
[07/Sep/2017 15:09:36] ERROR [django.server:131] "POST /restaurantes/add/ HTTP/1.1" 500 76455
[07/Sep/2017 15:09:58] INFO [restaurantes.views:91] 2017-09-07 15:09:58 - se ha consultado la página de add restaurante
[07/Sep/2017 15:10:01] INFO [restaurantes.views:48] 2017-09-07 15:10:01 - se ha consultado la página de restaurantes
[07/Sep/2017 15:10:19] INFO [restaurantes.views:48] 2017-09-07 15:10:19 - se ha consultado la página de restaurantes
